learning_rate : 0.0001
batch_size : 512
num_epochs : 50
nsamples : 300000
act_hidden_layer : elu
act_output_layer_mclass : softmax
act_output_layer_binary : sigmoid
loss_function_mclass : SparseCategoricalCrossentropy
loss_function_binary : binary_crossentropy
verbose : 1
patience : 5
verbose : 1
restore_best_weights : True
start_from_epoch : 10
monitor : 'val_accuracy'
decay_rate : 0.05
start_decay : 10
accuracy_threshold : 0.1
loss_threshold : 0.1
is_training : true
is_prediction : true
is_resampling : true
mass_norm  : true 
tree_name : tree
event_branch : T_event

# train_features: [
#    T_ptq1, T_ptq2,T_enq1, T_enq2,T_phiq1, T_phiq2,  T_etaq1, T_etaq2,T_mqq, T_norm_pt , T_dR_subleadqH,
#    T_phiA_bb_qq, T_alphaqq,T_HTT_rest_30,T_NJ_30,T_pzAll,T_btgb1, T_btgb2,T_dETAqq, T_dPHIqq
# ]
# train_features: [
#   T_qglq1, T_qglq2, T_ptq1,  T_phiq1, T_phiq2,  T_etaq1, T_etaq2,
#   T_NJ_30, T_alphaqq, T_mqq, T_dETAqq, T_dPHIqq, T_btgb1, T_btgb2, 
#   T_enq1,  T_phiA_bb_qq, T_dR_leadqH,  T_pzAll,
#    era
# ]
train_features: [
  T_qglq1, T_qglq2, T_ptq1, T_ptq2, T_phiq1, T_phiq2,  T_etaq1, T_etaq2,
  T_NJ_30, T_alphaqq, T_mqq, T_dETAqq, T_dPHIqq, T_btgb1, T_btgb2, T_HTT_rest_30,
  T_enq1, T_enq2, T_zep, T_phiA_bb_qq, T_dR_leadqH, T_norm_pt, T_dR_subleadqH,
  T_pzAll, era, T_minR
]

weight_features:
  - T_weight
  - T_HLTweight
  - T_PUweight
  - T_btag_weight_central
  - T_online_btag_weight
  - LUMI



train_mclass_files_labels:
  folder_path : /Users/sandeeppradhan/Desktop/VBF_Analysis_Folder/2022_pre_EE_Ntuples/DNN_Ntuples_Train/
  file_names_labels:
    - file_name: tree_JetMET_2022_btgsf_5perc.root
      label: 0
      branch_name: DNN_QCD
    - file_name: tree_VBFHto2B_M-125_dipoleRecoilOn_TuneCP5_13p6TeV_powheg-pythia8_2022_btgsf.root
      label: 1
      branch_name: DNN_VBF
    - file_name: tree_GluGluHto2B_M-125_TuneCP5_13p6TeV_powheg-minlo-pythia8_2022_btgsf.root
      label: 2
      branch_name: DNN_GGH
    - file_name: tree_TTto4Q_TuneCP5_13p6TeV_powheg-pythia8_2022_btgsf.root
      label: 3
      branch_name: DNN_TT
    - file_name: tree_Zto2Q-4Jets_2022_btgsf.root
      label: 4
      branch_name: DNN_Z2Q

train_biclass_files_labels:
  folder_path : /Users/sandeeppradhan/Desktop/VBF_Analysis_Folder/2022_pre_EE_Ntuples/DNN_Ntuples_Train/
  file_names_labels:
    - file_name: tree_JetMET_2022_btgsf_5perc.root
      label: 0
      branch_name: DNN_BiClass
    - file_name: tree_VBFHto2B_M-125_dipoleRecoilOn_TuneCP5_13p6TeV_powheg-pythia8_2022_btgsf.root
      label: 1
      branch_name: DNN_BiClass
full_data_path :   /Users/sandeeppradhan/Desktop/VBF_Analysis_Folder/2022_pre_EE_Ntuples/DNN_Ntuples_Train/tree_JetMET_2022_btgsf.root

prediction_files:
  folder_path : /Users/sandeeppradhan/Desktop/VBF_Analysis_Folder/2022_pre_EE_Ntuples/DNN_Ntuples_Train/
  file_names:
    - tree_JetMET_2022_btgsf.root
    - tree_JetMET_2022_btgsf_5perc.root
    - tree_VBFHto2B_M-125_dipoleRecoilOn_TuneCP5_13p6TeV_powheg-pythia8_2022_btgsf.root
    - tree_GluGluHto2B_M-125_TuneCP5_13p6TeV_powheg-minlo-pythia8_2022_btgsf.root
    - tree_TTto4Q_TuneCP5_13p6TeV_powheg-pythia8_2022_btgsf.root
    - tree_Zto2Q-4Jets_2022_btgsf.root
    - tree_QCD-4Jets_HT_TuneCP5_13p6TeV_madgraphMLM-pythia8_2022_btgsf.root
    - tree_Zto2Q-4Jets_2022_btgsf_JECUp.root
    - tree_Zto2Q-4Jets_2022_btgsf_JECDown.root
    - tree_Zto2Q-4Jets_2022_btgsf_JERUp.root
    - tree_Zto2Q-4Jets_2022_btgsf_JERDown.root
    - tree_Zto2Q-4Jets_2022_btgsf_PNetJECUp.root
    - tree_Zto2Q-4Jets_2022_btgsf_PNetJECDown.root
    - tree_GluGluHto2B_M-125_TuneCP5_13p6TeV_powheg-minlo-pythia8_2022_btgsf_JECUp.root
    - tree_GluGluHto2B_M-125_TuneCP5_13p6TeV_powheg-minlo-pythia8_2022_btgsf_JECDown.root
    - tree_GluGluHto2B_M-125_TuneCP5_13p6TeV_powheg-minlo-pythia8_2022_btgsf_JERUp.root
    - tree_GluGluHto2B_M-125_TuneCP5_13p6TeV_powheg-minlo-pythia8_2022_btgsf_JERDown.root
    - tree_GluGluHto2B_M-125_TuneCP5_13p6TeV_powheg-minlo-pythia8_2022_btgsf_PNetJECUp.root
    - tree_GluGluHto2B_M-125_TuneCP5_13p6TeV_powheg-minlo-pythia8_2022_btgsf_PNetJECDown.root
    - tree_VBFHto2B_M-125_dipoleRecoilOn_TuneCP5_13p6TeV_powheg-pythia8_2022_btgsf_JECUp.root
    - tree_VBFHto2B_M-125_dipoleRecoilOn_TuneCP5_13p6TeV_powheg-pythia8_2022_btgsf_JECDown.root
    - tree_VBFHto2B_M-125_dipoleRecoilOn_TuneCP5_13p6TeV_powheg-pythia8_2022_btgsf_JERUp.root
    - tree_VBFHto2B_M-125_dipoleRecoilOn_TuneCP5_13p6TeV_powheg-pythia8_2022_btgsf_JERDown.root
    - tree_VBFHto2B_M-125_dipoleRecoilOn_TuneCP5_13p6TeV_powheg-pythia8_2022_btgsf_PNetJECUp.root
    - tree_VBFHto2B_M-125_dipoleRecoilOn_TuneCP5_13p6TeV_powheg-pythia8_2022_btgsf_PNetJECDown.root
    
  
output_plot_models:
  folder_path : /Users/sandeeppradhan/Desktop/VBF_Analysis_Folder/DNN_RESULTS/MClass_DNN_VBF/output_plot_models/
  mclass_dnn_file_names:
    roc_plot : roc_mclass_dnn.png
    mbb_distr_with_and_without_cut : mbb_distr_with_and_without_cut_mclass_dnn.png
    dnn_score_distr : dnn_score_distr_mclass_dnn.png
    odd_model : odd_mclass_dnn.keras
    even_model : even_mclass_dnn.keras
  biclass_dnn_file_names:
    roc_plot : roc_mclass_dnn.png
    mbb_distr_with_and_without_cut : mbb_distr_with_and_without_cut_biclass_dnn.png
    dnn_score_distr : dnn_score_distr_biclass_dnn.png
    odd_model : odd_biclass_dnn.keras
    even_model : even_biclass_dnn.keras
  biclass_bdt_file_names:
    roc_plot : roc_biclass_bdt.png
    mbb_distr_with_and_without_cut : mbb_distr_with_and_without_cut_biclass_bdt.png
    dnn_score_distr : dnn_score_distr_biclass_bdt.png
    odd_model : odd_biclass_bdt.keras
    even_model : even_biclass_bdt.keras

variable_distribution_files:
  save_folder_path : /Users/sandeeppradhan/Desktop/VBF_Analysis_Folder/DNN_RESULTS/MClass_DNN_VBF/output_plot_models/
  input_folder_path : /Users/sandeeppradhan/Desktop/VBF_Analysis_Folder/2022_pre_EE_Ntuples/DNN_Ntuples_Train/
  file_names_legend_colors:
    - file_name : tree_JetMET_2022_btgsf_5perc.root
      legend : JetMET 2022 5%
      color : blue
    - file_name : tree_VBFHto2B_M-125_dipoleRecoilOn_TuneCP5_13p6TeV_powheg-pythia8_2022_btgsf.root
      legend : VBFHto2B M-125
      color : red
    - file_name : tree_GluGluHto2B_M-125_TuneCP5_13p6TeV_powheg-minlo-pythia8_2022_btgsf.root
      legend : GluGluHto2B M-125
      color : green
    - file_name : tree_TTto4Q_TuneCP5_13p6TeV_powheg-pythia8_2022_btgsf.root
      legend : TTto4Q
      color : orange
    - file_name : tree_Zto2Q-4Jets_2022_btgsf.root
      legend : Zto2Q-4Jets HT
      color : purple
    - file_name : tree_QCD-4Jets_HT_TuneCP5_13p6TeV_madgraphMLM-pythia8_2022_btgsf.root
      legend : QCD-4Jets HT
      color : cyan

roc_curve_files:
  save_folder_path : /Users/sandeeppradhan/Desktop/VBF_Analysis_Folder/DNN_RESULTS/MClass_DNN_VBF/output_plot_models/
  input_folder_path : /Users/sandeeppradhan/Desktop/VBF_Analysis_Folder/2022_pre_EE_Ntuples/DNN_Ntuples_Train/
  file_names_labels:
    - file_name : tree_VBFHto2B_M-125_dipoleRecoilOn_TuneCP5_13p6TeV_powheg-pythia8_2022_btgsf.root
      label : 1
    - file_name : tree_QCD-4Jets_HT_TuneCP5_13p6TeV_madgraphMLM-pythia8_2022_btgsf.root
      label : 0
  file_names_loss_acc_train_val:
    bdt_biclass_even_file_name : loss_acc_train_val_biclass_bdt_even.png
    bdt_biclass_odd_file_name : loss_acc_train_val_biclass_bdt_odd.png
    dnn_mclass_even_file_name : loss_acc_train_val_mclass_dnn_even.png
    dnn_mclass_odd_file_name : loss_acc_train_val_mclass_dnn_odd.png
    dnn_biclass_even_file_name : loss_acc_train_val_biclass_dnn_even.png
    dnn_biclass_odd_file_name : loss_acc_train_val_biclass_dnn_odd.png


mbb_distribution_files_dnn_cuts:
  file_path : /Users/sandeeppradhan/Desktop/VBF_Analysis_Folder/2022_pre_EE_Ntuples/DNN_Ntuples_Train/tree_JetMET_2022_btgsf.root
  dnn_cuts:
    - dnn_cut : 0
      legend : DNN Cut > 0
    - dnn_cut : 0.95
      legend : DNN Cut > 0.95

# event cut 
train_event_cut_branches : 
  - T_btgb1
  - T_btgb2
  - T_mqq
  - T_dETAqq
train_cuts : 
  - 0.2605
  - 0.2605
  - 500
  - 3.5

prediction_event_cut_branches : 
  - T_btgb1
  - T_btgb2
prediction_cuts : 
  - 0.2605
  - 0.2605



output_log :
  folder_path : /Users/sandeeppradhan/Desktop/VBF_Analysis_Folder/DNN_RESULTS/MClass_DNN_VBF/output_plot_models/
  file_name : log_history.txt




